### ISSUE TITLE
Hai ^-^

### ISSUE THREAD

**Issue by martin-esparragoza** [MmTtDeveloper/Godot-Engine-3D-LOD#2]
Help!!111 I TRY TO PASTE ARRAS.IO INTO GODOT AND ADD LOD AND IT NO WORKdjisajdisa IM SO SAD RN JDISA :((((((((((((((( PLS STOP BULLY ME

**Comment by BlueCannonBall** [comment]
What..?

**Comment by martin-esparragoza** [comment]
THIS IS SO SAD MY ARRAS.IO SKID VERSION NO WORK111111

**Comment by martin-esparragoza** [comment]
JDIJASIDJSA IDJSAIJD SAIJDIASJDOASJ DOASIDJ ASIDJSIA JDSIDJAOS IJSA @BlueCannonBall  STOP

**Comment by BlueCannonBall** [comment]
> JDIJASIDJSA IDJSAIJD SAIJDIASJDOASJ DOASIDJ ASIDJSIA JDSIDJAOS IJSA @BlueCannonBall  STOP

Gtfo
